### PR TITLE
fixes netherland language name

### LINKED ISSUE #217: Dutch translation appears as 'nl' not 'Nederlands'
In the UI, Dutch should appear as 'Nederlands' and not the country code `nl`. 

@ghengeveld can you confirm that this is how the language is printed in Dutch (as a native speaker). See the screenshot below. 

Screen Shot 2019-11-13 at 1 02 04 PM

### PR DESCRIPTION
**Pull request by jonniebigodes**
I was keeping an eye on the translation effort and saw that it was merged. Saw that the language was not corrected. And with that his small pr fixes and closes #217.

### CODE REVIEW

File: src/lib/getLanguageName.js [hunk 1]
```diff
@@ -4,6 +4,7 @@ const languageNameMap = {
   'zh-CN': '简体中文',
   'zh-TW': '繁體中文',
   pt: 'Português',
+  nl:'Nederlands'
```
Comment (kylesuss) [inline src/lib/getLanguageName.js]:
```suggestion
  nl: 'Nederlands',
```

**Comment by jonniebigodes** [comment]
@kylesuss i already had it lined up, i didn't push it just yet, because i was working on the angular documentation and i got sidelined. The issue then reminded me of that.
